# Site
repository: luislofer89/luislofer89.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis López Fernández
title: R&D Project Manager and Machine Learning Engineer
email: luislofer89@gmail.com
website: luislf.xyz

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: luislofer89
github_username:  luislofer89
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: luisloez89
linkedin_username: luislopezfdez
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_1.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Hexagon
        link: https://hexagon.com/
        link_text: www.hexagon.com
        sub_title: R&D Project Manager and Machine Learning Engineer
        caption: July 2020 - Present
        quote: >
          *TODO*: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
        description: | # this will include new lines to allow paragraphs
          *TODO*: Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.  
          
      - layout: left
        border: weak
        title: CTAG
        link: https://ctag.com/en/
        link_text: www.ctag.com
        sub_title: R&D Project Manager and Computer Vision Engineer
        caption: March 2018 - June 2020
        quote: >
          Research and development of calibration and perception algorithms for several "Car Makers" and "Tier 1" suppliers. 
        description: | # this will include new lines to allow paragraphs
          Filtering, semantic segmentation, clustering, oriented bounding box estimation and object tracking algorithms, among others, for camera, RADAR and LiDAR sensors.
  
      - layout: left
        border: weak
        title: INSITU Engineering
        link: https://ingenieriainsitu.com/en/
        link_text: www.ingenieriainsitu.com
        sub_title: R&D Project Manager and Computer Vision Engineer
        caption: July 2016 - February 2018
        quote: >
          Research and development. 
        description: | # this will include new lines to allow paragraphs
          Development of calibration, Artificial Intelligence and Computer Visión algorithms for asset detection, classification, description and tracking in MMS (Mobile Mapping System) and UAV (Unmanhed Aerial Vehicle) data, mainly acquired with GNSS, LiDAR and imaging sensors.

      - layout: left
        border: weak
        title: TIDOP Research Group - University of Salamanca
        link: https://tidop.usal.es/
        link_text: www.tidop.usal.es
        sub_title: Computer Vision Researcher
        caption: August 2014 - June 2016
        quote: >
          Research and development. 
        description: | # this will include new lines to allow paragraphs
          Development of a research line focused on the application of geomatic strategies (LiDAR and imaging acquisition and processing) for the optimization of energetic resources, as well as collaboration in numerous research projects.  Currently I continue to collaborate with the research group as an external consultant on Computer Vision and Artificial Intelligence issues.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: University of Salamanca
        caption: 2013 - 2017
        sub_title: PhD in Geotechnologies applied to Construction, Energy and Industry
        quote: >
          TODO: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
        description: | # this will include new lines to allow paragraphs
          Development of Computer Vision solutions for the automatic analysis of geomatic products (LiDAR/Photogrammetric Point Clouds and Multispectral Imagery) applied to the management of energy resources.

      - layout: left
        border: weak
        title: University of Salamanca
        caption: 2012 - 2013
        sub_title: Master's Degree in Cartographic Geotechnologies applied to engineering and Architecture
        quote: >
          *TODO*: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
        description: | # this will include new lines to allow paragraphs
          *TODO*: Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.  

      - layout: left
        border: weak
        title: University of Oviedo
        caption: 2007 - 2011
        sub_title: Bachelor's Degree in Surveying Engineering
        quote: >
          *TODO*: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
        description: | # this will include new lines to allow paragraphs
          *TODO*: Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.  

      - layout: left
        border: weak
        title: CIFP of Avilés
        caption: 2014 - 2016
        sub_title: Certificate of Higher Education in Multiplatform Applications Development
        quote: >
          *TODO*: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
        description: | # this will include new lines to allow paragraphs
          *TODO*: Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.  

      - layout: left
        border: weak
        title: CIFP of Avilés
        caption: 2014 - 2016
        sub_title: Certificate of Higher Education in WEB Applications Development
        quote: >
          *TODO*: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
        description: | # this will include new lines to allow paragraphs
          *TODO*: Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.  


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
